services:
  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/OrderService/Order.API/Dockerfile


  rabbitmq:
    image: rabbitmq:management

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/ProductService/Product.API/Dockerfile