services:
  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/OrderService/Order.API/Dockerfile


  rabbitmq:
    image: rabbitmq:management

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/ProductService/Product.API/Dockerfile
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
  
  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.2
        

networks:
  elastic:
    driver: bridge
    
volumes: 
   elasticsearch-data: